### ISSUE TITLE
no support linux

### ISSUE THREAD

**Issue by evilbinary** [hlpp/scheme#6]
no support linux

**Comment by evilbinary** [comment]
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;作者:evilbinary on 2017-08-11 20:40:56.
;邮箱:rootdebug@163.com
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(library (  ) 
  (export delayMS
  clearText
  pauseHere
  simpleRing
  setTextColor
  getTextColor
  setBackColor
  getBackColor
  setColors
  setSwapColors
  setUnderLine
  getLineWidth
  getLineNum
  getCursorX
  getCursorY
  gotoTextPos
  setCursorVisible
  setCursorSize
  getConsoleTitle
  setConsoleTitle
  fixConsoleSize
  jkGetKey
  jkHasKey)

 (import (scheme) (utils libutil) (cffi cffi) )

 (define lib-name
  (case (machine-type)
   ((arm32le) ".so")
   ((a6nt i3nt) ".dll")
   ((a6osx i3osx)  ".so")
   ((a6le i3le) ".so")))
 (define lib (load-librarys  lib-name ))

;;void delayMS(uint32 d)
(def-function delayMS
             "delayMS" (uint32) void)

;;void clearText(void )
(def-function clearText
             "clearText" (void) void)

;;void pauseHere(void )
(def-function pauseHere
             "pauseHere" (void) void)

;;int simpleRing(uint16 freq ,uint16 len)
(def-function simpleRing
             "simpleRing" (uint16 uint16) int)

;;int setTextColor(uint8 fColor)
(def-function setTextColor
             "setTextColor" (uint8) int)

;;PCCOLOR getTextColor(void )
(def-function getTextColor
             "getTextColor" (void) PCCOLOR)

;;int setBackColor(uint8 bColor)
(def-function setBackColor
             "setBackColor" (uint8) int)

;;PCCOLOR getBackColor(void )
(def-function getBackColor
             "getBackColor" (void) PCCOLOR)

;;int setColors(uint8 fColor ,uint8 bColor)
(def-function setColors
             "setColors" (uint8 uint8) int)

;;int setSwapColors(int b)
(def-function setSwapColors
             "setSwapColors" (int) int)

;;int setUnderLine(int b)
(def-function setUnderLine
             "setUnderLine" (int) int)

;;uint8 getLineWidth(void )
(def-function getLineWidth
             "getLineWidth" (void) uint8)

;;uint8 getLineNum(void )
(def-function getLineNum
             "getLineNum" (void) uint8)

;;uint8 getCursorX(void )
(def-function getCursorX
             "getCursorX" (void) uint8)

;;uint8 getCursorY(void )
(def-function getCursorY
             "getCursorY" (void) uint8)

;;int gotoTextPos(uint8 x ,uint8 y)
(def-function gotoTextPos
             "gotoTextPos" (uint8 uint8) int)

;;int setCursorVisible(int b)
(def-function setCursorVisible
             "setCursorVisible" (int) int)

;;int setCursorSize(uint8 s)
(def-function setCursorSize
             "setCursorSize" (uint8) int)

;;int getConsoleTitle(char* title ,uint8 len)
(def-function getConsoleTitle
             "getConsoleTitle" (string uint8) int)

;;int setConsoleTitle(char* title)
(def-function setConsoleTitle
             "setConsoleTitle" (string) int)

;;int fixConsoleSize(uint16 width ,uint16 height)
(def-function fixConsoleSize
             "fixConsoleSize" (uint16 uint16) int)

;;uint16 jkGetKey(void )
(def-function jkGetKey
             "jkGetKey" (void) uint16)

;;int jkHasKey(void )
(def-function jkHasKey
             "jkHasKey" (void) int)


)

**Comment by evilbinary** [comment]
can not run on https://github.com/evilbinary/scheme-lib.

**Comment by hlpp** [comment]
advertising again

**Comment by evilbinary** [comment]
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;作者:evilbinary on 2017-08-11 20:45:35.
;邮箱:rootdebug@163.com
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(library (  ) 
  (export delayMS
  clearText
  pauseHere
  simpleRing
  setTextColor
  getTextColor
  setBackColor
  getBackColor
  setColors
  setSwapColors
  setUnderLine
  getLineWidth
  getLineNum
  getCursorX
  getCursorY
  gotoTextPos
  setCursorVisible
  setCursorSize
  getConsoleTitle
  setConsoleTitle
  fixConsoleSize
  jkGetKey
  jkHasKey)

 (import (scheme) (utils libutil) (cffi cffi) )

 (define lib-name
  (case (machine-type)
   ((arm32le) ".so")
   ((a6nt i3nt) ".dll")
   ((a6osx i3osx)  ".so")
   ((a6le i3le) ".so")))
 (define lib (load-librarys  lib-name ))

;;void delayMS(uint32 d)
(def-function delayMS
             "delayMS" (uint32) void)

;;void clearText(void )
(def-function clearText
             "clearText" (void) void)

;;void pauseHere(void )
(def-function pauseHere
             "pauseHere" (void) void)

;;int simpleRing(uint16 freq ,uint16 len)
(def-function simpleRing
             "simpleRing" (int int) int)

;;int setTextColor(uint8 fColor)
(def-function setTextColor
             "setTextColor" (int) int)

;;PCCOLOR getTextColor(void )
(def-function getTextColor
             "getTextColor" (void) PCCOLOR)

;;int setBackColor(uint8 bColor)
(def-function setBackColor
             "setBackColor" (int) int)

;;PCCOLOR getBackColor(void )
(def-function getBackColor
             "getBackColor" (void) PCCOLOR)

;;int setColors(uint8 fColor ,uint8 bColor)
(def-function setColors
             "setColors" (int int) int)

;;int setSwapColors(int b)
(def-function setSwapColors
             "setSwapColors" (int) int)

;;int setUnderLine(int b)
(def-function setUnderLine
             "setUnderLine" (int) int)

;;uint8 getLineWidth(void )
(def-function getLineWidth
             "getLineWidth" (void) int)

;;uint8 getLineNum(void )
(def-function getLineNum
             "getLineNum" (void) int)

;;uint8 getCursorX(void )
(def-function getCursorX
             "getCursorX" (void) int)

;;uint8 getCursorY(void )
(def-function getCursorY
             "getCursorY" (void) int)

;;int gotoTextPos(uint8 x ,uint8 y)
(def-function gotoTextPos
             "gotoTextPos" (int int) int)

;;int setCursorVisible(int b)
(def-function setCursorVisible
             "setCursorVisible" (int) int)

;;int setCursorSize(uint8 s)
(def-function setCursorSize
             "setCursorSize" (int) int)

;;int getConsoleTitle(char* title ,uint8 len)
(def-function getConsoleTitle
             "getConsoleTitle" (string int) int)

;;int setConsoleTitle(char* title)
(def-function setConsoleTitle
             "setConsoleTitle" (string) int)

;;int fixConsoleSize(uint16 width ,uint16 height)
(def-function fixConsoleSize
             "fixConsoleSize" (int int) int)

;;uint16 jkGetKey(void )
(def-function jkGetKey
             "jkGetKey" (void) int)

;;int jkHasKey(void )
(def-function jkHasKey
             "jkHasKey" (void) int)


)

the snake cannot run on this code for scheme-lib
